services:
  - type: web
    name: mern-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://bhaveshm:alpine-master@cluster0.2cuxt.mongodb.net/chatAppAlpine?retryWrites=true&w=majority&appName=Cluster0
